### ISSUE TITLE
Postgres DB Migration Script

### ISSUE THREAD

**Issue by rexdivakar** [Abhinav-26/Automated-Scripts#1]
I have created a shell script which migrates the database on schema level from one database instance to another without any downtime. This also takes a quick snapshot of the entire contents of the DB and stores in for later needs for disaster recovery needs.

**Comment by Abhinav-26** [comment]
> I have created a shell script which migrates the database on schema level from one database instance to another without any downtime. This also takes a quick snapshot of the entire contents of the DB and stores in for later needs for disaster recovery needs.

Great, merged it.
